<table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Brand</th>
                <th>Desc</th>
                <th>SizeSet</th>
                <th>StyleNo</th>
                <th>BuyerCode</th>
                <th>SKUType</th>
                <th>VendorCode</th>
                <th>SRP</th>
                <th>UPC</th>
                <th>Uom</th>
                <th>SKU</th>
                <th>Dept</th>
                <th>SubDept</th>
                <th>Class</th>
                <th>SubClass</th>
                <th>PriceType</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Brand</th>
                <th>Desc</th>
                <th>SizeSet</th>
                <th>StyleNo</th>
                <th>BuyerCode</th>
                <th>SKUType</th>
                <th>VendorCode</th>
                <th>SRP</th>
                <th>UPC</th>
                <th>Uom</th>
                <th>SKU</th>
                <th>Dept</th>
                <th>SubDept</th>
                <th>Class</th>
                <th>SubClass</th>
                <th>PriceType</th>
            </tr>
        </tfoot>
    </table>